"""dropped profile_images

Revision ID: 1148a22616ee
Revises: b65f550d4529
Create Date: 2022-06-14 21:55:51.292087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1148a22616ee'
down_revision = 'b65f550d4529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    op.drop_column('user', 'profile_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image', sa.VARCHAR(length=32), nullable=True))
    op.drop_column('user', 'avatar_hash')
    # ### end Alembic commands ###
