"""adding subject column on message table

Revision ID: 23f6b384cae4
Revises: 54d71e347c09
Create Date: 2022-06-19 12:06:13.286904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f6b384cae4'
down_revision = '54d71e347c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('subject', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'subject')
    # ### end Alembic commands ###
