"""contact message added

Revision ID: 362c450ff090
Revises: 38987dd3642e
Create Date: 2022-06-16 20:11:27.111383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362c450ff090'
down_revision = '38987dd3642e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
