"""project sections added

Revision ID: b65f550d4529
Revises: f423f1721fe0
Create Date: 2022-06-14 19:17:18.385861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b65f550d4529'
down_revision = 'f423f1721fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_sections', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'project_sections')
    # ### end Alembic commands ###
