"""article sections added

Revision ID: f423f1721fe0
Revises: 5aa5765a8cea
Create Date: 2022-06-14 19:01:53.182766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f423f1721fe0'
down_revision = '5aa5765a8cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('article_sections', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'article_sections')
    # ### end Alembic commands ###
